//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.02 at 06:28:08 PM SAMT 
//


package com.topografix.gpx._1._1;

import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;


@Root(name="gpx")
public class GpxType {

    @Element(required=false)
	protected MetadataType metadata;
    @ElementList(required=false, inline=true)
    protected List<WptType> wpt = new ArrayList<WptType>();
    //@Element(required=false)
    //protected List<RteType> rte = new ArrayList<RteType>();
    @ElementList(inline=true)
    protected List<TrkType> trk = new ArrayList<TrkType>();
    @Element(required=false)
    protected ExtensionsType extensions;
    
    @Attribute
    protected String version;
    @Attribute
    protected String creator;

    
    
    
    public MetadataType getMetadata() {
        return metadata;
    }

    public void setMetadata(MetadataType value) {
        this.metadata = value;
    }

    public List<WptType> getWpt() {
        //if (wpt == null) {
        //    wpt = new ArrayList<WptType>();
        //}
        return this.wpt;
    }

    /*
    public List<RteType> getRte() {
        if (rte == null) {
            rte = new ArrayList<RteType>();
        }
        return this.rte;
    }
    */

    public List<TrkType> getTrk() {
        if (trk == null) {
            trk = new ArrayList<TrkType>();
        }
        return this.trk;
    }

    public ExtensionsType getExtensions() {
        return extensions;
    }

    public void setExtensions(ExtensionsType value) {
        this.extensions = value;
    }

    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    public void setVersion(String value) {
        this.version = value;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String value) {
        this.creator = value;
    }

}
